### ISSUE TITLE
Archive Problem in Xcode 16 After update Xcode

### ISSUE THREAD

**Issue by Pragnesh-4917** [maplibre/maplibre-react-native#449] opened 2024-09-20 03:57 UTC
I'm encountering an issue where the Archive build process fails in Xcode 16 after pushing changes to GitHub. The project builds and runs successfully on the simulator and real devices, but when I attempt to create an Archive build, the process fails.

<img width="498" alt="Screenshot 2024-09-19 at 1 25 27 PM" src="https://github.com/user-attachments/assets/2474ba12-7fe4-47c4-9f52-a2dd3c48727a">

**Comment by HarshaZeitview** [comment] 2024-09-20 10:49
Hi @Pragnesh-4917 
so you need to write a **Script on build phases**.

```
# Xcode version validation script
if [ "$XCODE_VERSION_MAJOR" = "1500" ]; then
 echo "Remove signature files (Xcode 15 workaround)"

 # Remove signature files
 rm "$BUILD_DIR/Release-iphoneos/*.signature"
fi
```

so make sure you check the "**For Install builds only**".
then try to re run the project and try with Archive.

**Comment by Pragnesh-4917** [comment] 2024-09-20 11:27
we do it but still not working

**Comment by madmeatballs** [comment] 2024-09-20 16:01
> Hi @Pragnesh-4917 so you need to write a **Script on build phases**.
> 
> ```
> # Xcode version validation script
> if [ "$XCODE_VERSION_MAJOR" = "1500" ]; then
>  echo "Remove signature files (Xcode 15 workaround)"
> 
>  # Remove signature files
>  rm "$BUILD_DIR/Release-iphoneos/*.signature"
> fi
> ```
> 
> so make sure you check the "**For Install builds only**". then try to re run the project and try with Archive.

Yes, this is more like a workaround. I also do this for the meantime and it disrupts our workflow. Hoping this will be solved.

**Comment by tyrauber** [comment] 2024-09-21 08:42
Duplicate of #442. [Please try `10.0.0-alpha.15`](https://github.com/maplibre/maplibre-react-native/issues/442#issuecomment-2365063318) .

**Comment by Pragnesh-4917** [comment] 2024-09-23 11:32
Still we are getting this error 		"@maplibre/maplibre-react-native": "^10.0.0-alpha.15",

**Comment by tyrauber** [comment] 2024-09-24 10:28
Please try `10.0.0-alpha.17`.

**Closed by tyrauber** 2024-09-24 10:28 UTC

**Comment by eTryp** [comment] 2024-09-24 13:12
Alpha.17 with the script included on the build phase is working fine on bare workflow

**Comment by Pragnesh-4917** [comment] 2024-09-25 04:34
please send me which script add

**Comment by madmeatballs** [comment] 2024-09-25 04:55
> Please try `10.0.0-alpha.17`.

our project works now but still getting issues when uploading to app store connect. I created a new issue for it https://github.com/maplibre/maplibre-react-native/issues/456

**Comment by tousif-v** [comment] 2024-09-25 06:45
try this 

# Xcode version validation script
if [ "$XCODE_VERSION_MAJOR" = "1600" ] || [ "$XCODE_VERSION_MAJOR" = "1500" ]; then
 echo "Remove signature files (Xcode 16 workaround)"

 # Remove signature files
 rm -rf "$CONFIGURATION_BUILD_DIR/MapLibre.xcframework-ios.signature";
fi
