### ISSUE TITLE
Maplibre.UserLocation doesn't work

### ISSUE THREAD

**Issue by szk5** [maplibre/maplibre-react-native#457] opened 2024-09-25 09:09 UTC
Hello,

We found a a bug?, when we tried to use MapLibreGL.UserLocaton and FollowUserLocation with Maplibre 10

<MapLibreGL.UserLocation androidRenderMode="compass" showsUserHeadingIndicator={true} onUpdate={onLocationUpdate} />
<MapLibreGL.Camera ref={cameraRef} {...mapOption} followUserMode='normal' />

We call this code snipppet from async function.
The problems are the following: 
- the userlocation is sometimes work but not correct sometimes not work
- the followUserMode doesn't work

We use Maplibre 10 and they are don't work but 
in the Maplibre 9 location okk
Following works on emulator but doesn't  work on phone Google Pixel

Thank you for your help.

**Comment by KiwiKilian** [comment] 2024-10-11 08:08
This is hardly a minimal reproduction. It's unclear what props you are actually passing to `MapLibreGL.Camera`.

**Comment by KiwiKilian** [comment] 2024-11-21 05:59
Closing due to incomplete reproduction.

**Closed by KiwiKilian** 2024-11-21 05:59 UTC
